# Generated by Django 3.2.16 on 2024-06-18 09:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_follow_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_constraint',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'following')},
        ),
    ]
